object Versions {
    const val coreKtx="1.9.0"
    const val appcompat="1.6.1"
    const val material="1.9.0"
    const val lifecycleRuntimeKtx="2.6.1"
    const val activityCompose="1.7.2"
    const val compose="2023.03.00"
    const val navigationCompose="2.7.6"
    const val lifecycleViewModelKtx="2.7.0"
    const val hilt="2.48"
    const val hiltCompiler="2.48"
    const val hiltKapt="1.1.0"
    const val hiltNavigationCompose="1.2.0-beta01"

    const val retrofit="2.9.0"
    const val okhttp="5.0.0-alpha.2"
    const val gsonConverter="2.9.0"
    const val moshi="1.13.0"
    const val moshiConverter="2.9.0"
    const val loggingInterceptor="4.9.1"
    const val coroutines="1.7.1"
    const val splashScreen="1.0.1"
    const val coil="2.5.0"
}